package com.tt.calorie.common.authorization;

public enum Permission {
    CRUD_USER,
    PATCH_CALORIE_LIMIT_FOR_SELF_ONLY,
    CREATE_CALORIE_INTAKE_ENTRY_FOR_SELF_ONLY,
    CREATE_CALORIE_INTAKE_ENTRY,
    READ_CALORIE_INTAKE_ENTRY_FOR_SELF_ONLY,
    READ_CALORIE_INTAKE_ENTRY,
    UPDATE_CALORIE_INTAKE_ENTRY,
    DELETE_CALORIE_INTAKE_ENTRY
}
